### ISSUE TITLE
Missing Mount

### ISSUE THREAD

**Issue by Xocolo** [tiker/GoGoMount#12]
The Crusader's Direhorn - the Zandalari Paladin Mount - Has not been added and cannot be used with Gogomount

**Comment by tiker** [comment]
There might be a few new mounts from the last patch.  I'll go through and add them all this weekend.

**Comment by Xocolo** [comment]
I tried pasting in the new LUA file but it still comes up with "GoGo: An unknown mount has appeared in you list of mounts. Please report this so that it can be added to future versions of GoGoMount".

**Comment by tiker** [comment]
There's a few more mounts to add.  Working on adding them now.
